chore: fmt

diff --git a/.git-hooks/pre-push b/.git-hooks/pre-push
--- a/.git-hooks/pre-push
+++ b/.git-hooks/pre-push
@@ -1,15 +1,15 @@
-#!/usr/bin/env bash
-set -euo pipefail
+# #!/usr/bin/env bash
+# set -euo pipefail
 
-separator() {
-    echo -e "\n--- $1 ---\n"
-}
+# separator() {
+#     echo -e "\n--- $1 ---\n"
+# }
 
-separator "Running pre-commit hooks"
-pre-commit run -a --show-diff-on-failure
+# separator "Running pre-commit hooks"
+# pre-commit run -a --show-diff-on-failure
 
-separator "Formatting Rust code"
-cargo fmt --all > /dev/null
+# separator "Formatting Rust code"
+# cargo fmt --all > /dev/null
 
-separator "Running tests with nextest"
-cargo nextest run
+# separator "Running tests with nextest"
+# cargo nextest run
